test

diff --git a/.gitlab/workflows/.gitlab-ci.yml b/.gitlab/workflows/.gitlab-ci.yml
--- a/.gitlab/workflows/.gitlab-ci.yml
+++ b/.gitlab/workflows/.gitlab-ci.yml
@@ -86,17 +86,17 @@ check_firmware_version:
       echo "Success: FIRMWARE_VERSION or VERSION has changed.";
       fi
 
-validate_tracker:
-  stage: validate
-  script:
-    - echo "Aggregating validate stage results..."
-    # Fail this job if any of the validate jobs failed
-    - if [[ "$CI_JOB_STATUS" == "failed" ]]; then exit 1; else exit 0; fi
-  needs:
-    - restrict_pr_to_main
-    - check_pr_description
-    - check_firmware_version
-  allow_failure: true
+# validate_tracker:
+#   stage: validate
+#   script:
+#     - echo "Aggregating validate stage results..."
+#     # Fail this job if any of the validate jobs failed
+#     - if [[ "$CI_JOB_STATUS" == "failed" ]]; then exit 1; else exit 0; fi
+#   needs:
+#     - restrict_pr_to_main
+#     - check_pr_description
+#     - check_firmware_version
+#   allow_failure: true
 
 build_dev:
   stage: build
