adjusted

diff --git a/.github/workflows/check_version_for_tag.yaml b/.github/workflows/check_version_for_tag.yaml
--- a/.github/workflows/check_version_for_tag.yaml
+++ b/.github/workflows/check_version_for_tag.yaml
@@ -1,4 +1,4 @@
-name: Check Firmware Version Change
+name: Check Firmware Version and Prod Devices Change
 
 on:
   pull_request:
@@ -6,7 +6,7 @@ on:
       - main
 
 jobs:
-  check-version-change:
+  check-version-and-devices-change:
     runs-on: ubuntu-latest
 
     steps:
@@ -35,12 +35,31 @@ jobs:
           echo "develop_firmware_version=$DEVELOP_FIRMWARE_VERSION" >> $GITHUB_ENV
           echo "develop_version=$DEVELOP_VERSION" >> $GITHUB_ENV
 
-      - name: Check if versions have changed
+      - name: Check for prod_devices.csv changes
+        id: check_devices_file
         run: |
-          # Compare versions from develop and main
-          if [[ "$main_firmware_version" == "$develop_firmware_version" ]] && [[ "$main_version" == "$develop_version" ]]; then
-            echo "Error: FIRMWARE_VERSION and VERSION have not changed."
-            exit 1
+          # Check if prod_devices.csv has changed in the current PR
+          if git diff --name-only origin/main | grep -q "^prod_devices.csv$"; then
+            echo "devices_file_changed=true" >> $GITHUB_ENV
           else
-            echo "Success: FIRMWARE_VERSION or VERSION has changed."
+            echo "devices_file_changed=false" >> $GITHUB_ENV
+          fi
+
+      - name: Check if versions or devices file have changed
+        run: |
+          # Load values from environment
+          source $GITHUB_ENV
+          # Check if either FIRMWARE_VERSION or VERSION has changed
+          if [[ "$main_firmware_version" == "$develop_firmware_version" ]] && [[ "$main_version" == "$develop_version" ]]; then
+            VERSION_CHANGED=false
+          else
+            VERSION_CHANGED=true
+          fi
+
+          # Check if all conditions for merging are met
+          if [[ "$VERSION_CHANGED" == "true" ]] && [[ "$devices_file_changed" == "true" ]]; then
+            echo "Success: Either FIRMWARE_VERSION or VERSION has changed, and prod_devices.csv has been modified."
+          else
+            echo "Error: Either FIRMWARE_VERSION or VERSION must change, and prod_devices.csv must also be modified."
+            exit 1
           fi
